In [1]:
import numpy as np


In [2]:
W = np.array([[0.1, 0.5],[-0.3, 0.8]]).T

In [3]:
W

array([[ 0.1, -0.3],
       [ 0.5,  0.8]])

In [4]:
X = np.array([[0.2, 0.1, 0.3], [0.4, 0.4, 0.1]]).T

In [15]:
X

array([[0.2, 0.4],
       [0.1, 0.4],
       [0.3, 0.1]])

In [17]:
print(np.argmax(X, axis=1))

[1 1 0]


In [6]:
scores = np.dot(X, W)

In [7]:
scores

array([[ 0.22,  0.26],
       [ 0.21,  0.29],
       [ 0.08, -0.01]])

In [8]:
loss =  np.linalg.norm(scores)

In [9]:
loss

0.5006995106848019

In [10]:
bias = np.array([0.01,0.02]).reshape((1,2))

In [11]:
scores_biased = scores + bias

In [12]:
scores_biased

array([[0.23, 0.28],
       [0.22, 0.31],
       [0.09, 0.01]])

In [13]:
loss_biased = np.linalg.norm(scores_biased)

In [40]:
print(loss_biased)

0.5329165037789692


In [14]:
np.log(0.64)

-0.4462871026284195